from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
import pandas as pd
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

def generate_pdf_report(analysis, document_name, output_path):
    """
    Generate PDF report from analysis results
    """
    try:
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        story = []
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a365d'),
            spaceAfter=30
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2c5282'),
            spaceAfter=12
        )
        
        # Title
        story.append(Paragraph("Financial Document Analysis Report", title_style))
        story.append(Spacer(1, 0.2 * inch))
        
        # Document Information
        story.append(Paragraph("Document Information", heading_style))
        info_data = [
            ['Document Name:', document_name],
            ['Analysis Date:', datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')],
            ['Analysis ID:', str(analysis['_id'])],
            ['Confidence Score:', f"{analysis['confidence']:.2%}"]
        ]
        
        info_table = Table(info_data, colWidths=[2*inch, 4*inch])
        info_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e2e8f0')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        
        story.append(info_table)
        story.append(Spacer(1, 0.3 * inch))
        
        # Financial Summary
        results = analysis.get('results', {})
        
        story.append(Paragraph("Financial Summary", heading_style))
        financial_summary = results.get('financialSummary', 'No summary available')
        story.append(Paragraph(financial_summary, styles['Normal']))
        story.append(Spacer(1, 0.2 * inch))
        
        # Risk Assessment
        story.append(Paragraph("Risk Assessment", heading_style))
        risk_assessment = results.get('riskAssessment', {})
        risk_score = risk_assessment.get('score', 0)
        risk_details = risk_assessment.get('details', 'No details available')
        
        story.append(Paragraph(f"<b>Risk Score:</b> {risk_score:.2f} (0=Low, 1=High)", styles['Normal']))
        story.append(Spacer(1, 0.1 * inch))
        story.append(Paragraph(f"<b>Details:</b> {risk_details}", styles['Normal']))
        story.append(Spacer(1, 0.2 * inch))
        
        # Market Insights
        if 'marketInsights' in results:
            story.append(Paragraph("Market Insights", heading_style))
            story.append(Paragraph(results['marketInsights'], styles['Normal']))
            story.append(Spacer(1, 0.2 * inch))
        
        # Recommendations
        story.append(Paragraph("Recommendations", heading_style))
        recommendations = results.get('recommendations', 'No recommendations available')
        story.append(Paragraph(recommendations, styles['Normal']))
        story.append(Spacer(1, 0.2 * inch))
        
        # Footer
        story.append(Spacer(1, 0.5 * inch))
        footer_text = "This report was automatically generated by Financial Document Analyzer AI System."
        story.append(Paragraph(footer_text, styles['Italic']))
        
        # Build PDF
        doc.build(story)
        
        logger.info(f"PDF report generated: {output_path}")
        
    except Exception as e:
        logger.error(f"Error generating PDF report: {str(e)}")
        raise

def generate_csv_report(analysis, document_name, output_path):
    """
    Generate CSV report from analysis results
    """
    try:
        results = analysis.get('results', {})
        
        # Prepare data for CSV
        data = {
            'Document Name': [document_name],
            'Analysis ID': [str(analysis['_id'])],
            'Analysis Date': [analysis.get('completed_at', datetime.utcnow()).strftime('%Y-%m-%d %H:%M:%S')],
            'Confidence Score': [f"{analysis['confidence']:.2%}"],
            'Financial Summary': [results.get('financialSummary', '')],
            'Risk Score': [results.get('riskAssessment', {}).get('score', '')],
            'Risk Details': [results.get('riskAssessment', {}).get('details', '')],
            'Market Insights': [results.get('marketInsights', '')],
            'Recommendations': [results.get('recommendations', '')]
        }
        
        # Add chart data if available
        charts_data = results.get('chartsData', {})
        if 'revenueTrend' in charts_data:
            revenue_trend = charts_data['revenueTrend']
            data['Revenue Trend (Years)'] = [', '.join([str(item.get('year', '')) for item in revenue_trend])]
            data['Revenue Trend (Values)'] = [', '.join([str(item.get('value', '')) for item in revenue_trend])]
        
        # Create DataFrame and save to CSV
        df = pd.DataFrame(data)
        df.to_csv(output_path, index=False)
        
        logger.info(f"CSV report generated: {output_path}")
        
    except Exception as e:
        logger.error(f"Error generating CSV report: {str(e)}")
        raise